### ISSUE TITLE
use of tox-docker does stops detox from working in parallel

### ISSUE THREAD

**Issue by ssbarnea** [dcrosta/tox-docker#2]
It seems that when you run `detox`, the tasks will run sequentially instead of running in parallel.

On the bright side, they still run, which is more than what I was expecting when I decided to try `detox` command :)

**Comment by dcrosta** [comment]
Hm, as far as I can tell, things are still running in parallel, at least for the projects I'm using docker with. Do you have a minimal project/tox.ini example that recreates the failure?

(I'm using detox 0.11, tox 2.7.0, and tox-docker 1.0.0)

**Comment by dcrosta** [comment]
(I'm closing this, but if you're still having this issue and can show me how to reproduce, we can re-open it)
