### ISSUE TITLE
Tox 3.0.0 compatibility

### ISSUE THREAD

**Issue by kbalonek** [dcrosta/tox-docker#4]
Tox 3.0.0 was released yesterday (2 April 2018), but tox-docker requires "tox < 3.0.0". Is it possible to relax this requirement? At the moment an attempt to run tox 3.0.0 with tox-docker 1.0.0 results in 
`PluginValidationError: Plugin 'docker' could not be loaded: (tox 3.0.0 (/j/workspace/xxxx/.tox-venv/site-packages), Requirement.parse('tox<3.0,>=2.7.0'))!`

**Comment by dcrosta** [comment]
I think I did that out of an abundance of caution (major version -> maybe backwards breaking changes). Can you test with tox 3 and if it works, send a PR?
